gfhfh

In [3]:
# Activity 2: Dealing with Duplicates & Redundancy

# Task A: Identifying Duplicate Records

# 7. Identify Complete Duplicates:
# - Load a dataset and identify duplicated rows.
# - Use Pandas to detect duplicates.






# 8. Identify Duplicates based on Specific Columns:
# - Check for duplicates in specified columns.







# 9. Count Duplicate Rows:
# - Calculate and print the number of duplicate rows.

import pandas as pd

# Create a sample dataset with intentional duplicates
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Bob', 'Charlie'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'IT', 'IT'],
    'Salary': [50000, 60000, 55000, 70000, 50000, 60000, 55000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# 7. Identify Complete Duplicates
complete_duplicates = df[df.duplicated()]
print("\n7. Complete Duplicate Rows:")
print(complete_duplicates)

# 8. Identify Duplicates based on Specific Columns (e.g., Name and Department)
col_duplicates = df[df.duplicated(subset=['Name', 'Department'])]
print("\n8. Duplicates based on 'Name' and 'Department':")
print(col_duplicates)

# 9. Count Duplicate Rows
total_duplicates = df.duplicated().sum()
print(f"\n9. Total number of complete duplicate rows: {total_duplicates}")

Original DataFrame:
   EmployeeID     Name Department  Salary
0         101    Alice         HR   50000
1         102      Bob         IT   60000
2         103  Charlie         IT   55000
3         104    David    Finance   70000
4         105      Eva         HR   50000
5         102      Bob         IT   60000
6         103  Charlie         IT   55000

7. Complete Duplicate Rows:
   EmployeeID     Name Department  Salary
5         102      Bob         IT   60000
6         103  Charlie         IT   55000

8. Duplicates based on 'Name' and 'Department':
   EmployeeID     Name Department  Salary
5         102      Bob         IT   60000
6         103  Charlie         IT   55000

9. Total number of complete duplicate rows: 2

In [4]:
# Task B: Deduplication Techniques

# 10. Remove Complete Duplicates:
# - Drop duplicate rows and keep only the first occurrence.






# 11. Subset Deduplication:
# - Remove duplicates based on a subset of columns.






# 12. Keep Last Occurrence:
# - Drop duplicates but keep the last occurrence in the dataset.





import pandas as pd

# Sample dataset with duplicates
data = {
    'EmployeeID': [101, 102, 103, 104, 105, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Bob', 'Charlie'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR', 'IT', 'IT'],
    'Salary': [50000, 60000, 55000, 70000, 50000, 60000, 55000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# 10. Remove Complete Duplicates (keep first)
df_no_duplicates = df.drop_duplicates()
print("\n10. DataFrame after removing complete duplicates (keep first):")
print(df_no_duplicates)

# 11. Subset Deduplication based on 'Name' and 'Department'
df_subset_dedup = df.drop_duplicates(subset=['Name', 'Department'])
print("\n11. DataFrame after removing duplicates based on 'Name' and 'Department':")
print(df_subset_dedup)

# 12. Keep Last Occurrence of Duplicates
df_last_occurrence = df.drop_duplicates(keep='last')
print("\n12. DataFrame after removing duplicates (keep last occurrence):")
print(df_last_occurrence)

Original DataFrame:
   EmployeeID     Name Department  Salary
0         101    Alice         HR   50000
1         102      Bob         IT   60000
2         103  Charlie         IT   55000
3         104    David    Finance   70000
4         105      Eva         HR   50000
5         102      Bob         IT   60000
6         103  Charlie         IT   55000

10. DataFrame after removing complete duplicates (keep first):
   EmployeeID     Name Department  Salary
0         101    Alice         HR   50000
1         102      Bob         IT   60000
2         103  Charlie         IT   55000
3         104    David    Finance   70000
4         105      Eva         HR   50000

11. DataFrame after removing duplicates based on 'Name' and 'Department':
   EmployeeID     Name Department  Salary
0         101    Alice         HR   50000
1         102      Bob         IT   60000
2         103  Charlie         IT   55000
3         104    David    Finance   70000
4         105      Eva         HR   50000

12. DataFrame after removing duplicates (keep last occurrence):
   EmployeeID     Name Department  Salary
0         101    Alice         HR   50000
3         104    David    Finance   70000
4         105      Eva         HR   50000
5         102      Bob         IT   60000
6         103  Charlie         IT   55000